### ISSUE TITLE
Q: Need more information

### ISSUE THREAD

**Issue by st-schneider** [VirtusLab/graphbuddy#7]
Could you get more into, what languages are supported, and what the server is for actually?
Could the graphbuddy used with any language server compliant server or is it only java?
It looks really cool but I have no idea if and how I could use it.

**Comment by mstrag** [comment]
Currently we have full support for scala language, however we are working to support TypeScript so it should be available soon. 
Server is responsible for indexing all tokens from Your code with semantic data, then in plugin extension You need to set address of running server which will feed extension with proper nodes & edges.

Please stay tune! In next weekend there should be some blog post when You can find some cool examples of what this extension can do 💪

**Comment by bm-stschneider** [comment]
Please keep in mind that the typescript language server also works for javascript files, please don't skip js

**Comment by chromafunk** [comment]
Please add support for Python too, this looks like a really useful extension. Thanks

**Comment by Lionad-Morotar** [comment]
Wonderful !!! TypeScript & JavaScript Please !!!

**Comment by mstrag** [comment]
thanks for your interest, it's really glad to hear that someone is waiting for this extension, 
Our current progress is that we are working on 2 parts:
1. Integrating our server within IDE extension (using LSP) after that it won't require any additional configuration - just download from marketplace and that's all.
2. Support for TypeScript (we decided to change our approach which require some core changes)

To summarise your comments:

- TypeScript: we are really near to finish it, we are planning to release it in April.
- JavaScript: It is not so easy because JS doesn't expose a compiler API, and JS is dynamically and weakly typed. We cannot guarantee stability of JS extension (semantic information included in it) 
- Python, Kotlin, Java - after TypeScript we will have discussion about next step, and we will consider supporting one of these languages. However we cannot promise anything.

If someone is interested in creating support for any of language, we are open for contribution :)

**Comment by liosedhel** [comment]
Hello :) 
Closing now, we are focused on scala and scala 3 supported currently - TypeScript was slightly over time but does not have the required stability unfortunately. If someone is interesting, integration with other languages can be achieved with now public schema https://github.com/VirtusLab/graphbuddy/blob/master/proto/graph_node.proto (it just a matter of storing .proto files under `.semanticgraphs` folder). We try to focus on one thing at a time and prove that it works for our users. With a growing number of happy users, we will try to extend our research. Hope we will manage 🤞 

All the best,
Krzysztof
